version: "3.8"

services:
  web:
    build: .
    container_name: apache_server
    ports:
      - "8080:80"
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

volumes:
  db-data:

networks:
  my_network:
