version: "3.8"

services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase 
    networks:
      - mynetwork  

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork  

volumes:
  mongo_data:

networks:
  mynetwork:
    driver: bridge
